all: SelectionSort InsertionSort MergeSort QuickSort HeapSort

SelectionSort: SelectionSort.c
	gcc SelectionSort.c -o SelectionSort

InsertionSort: InsertionSort.c
	gcc InsertionSort.c -o InsertionSort

MergeSort: MergeSort.c
	gcc -o MergeSort.c -o MergeSort

QuickSort: QuickSort.c
	gcc -o QuickSort.c -o QuickSort

HeapSort: HeapSort.c
	gcc -o HeapSort.c -o HeapSort

clean:
	rm *.o
